//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StopList.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а
        ///автентичен
        ///аз
        ///ако
        ///ала
        ///бе
        ///без
        ///беше
        ///би
        ///бивш
        ///бивша
        ///бившо
        ///бил
        ///била
        ///били
        ///било
        ///благодаря
        ///близо
        ///бъдат
        ///бъде
        ///бяха
        ///в
        ///вас
        ///ваш
        ///ваша
        ///вероятно
        ///вече
        ///взема
        ///ви
        ///вие
        ///винаги
        ///внимава
        ///време
        ///все
        ///всеки
        ///всички
        ///всичко
        ///всяка
        ///във
        ///въпреки
        ///върху
        ///г
        ///ги
        ///главен
        ///главна
        ///главно
        ///глас
        ///го
        ///година
        ///години
        ///годишен
        ///д
        ///да
        ///дали
        ///два
        ///двама
        ///двамата
        ///две
        ///двете
        ///ден
        ///днес
        ///дни
        ///до
        ///добра
        ///добре
        ///добро
        ///добър
        ///докато
        ///докога
        ///дори
        ///досега
        ///доста
        ///друг
        ///друга
        ///други
        ///е
        ///евтин
        ///едва
        ///един
        ///една
        ///еднаква        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bulgarianST {
            get {
                return ResourceManager.GetString("bulgarianST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i
        ///me
        ///my
        ///myself
        ///we
        ///our
        ///ours
        ///ourselves
        ///you
        ///your
        ///yours
        ///yourself
        ///yourselves
        ///he
        ///him
        ///his
        ///himself
        ///she
        ///her
        ///hers
        ///herself
        ///it
        ///its
        ///itself
        ///they
        ///them
        ///their
        ///theirs
        ///themselves
        ///what
        ///which
        ///who
        ///whom
        ///this
        ///that
        ///these
        ///those
        ///am
        ///is
        ///are
        ///was
        ///were
        ///be
        ///been
        ///being
        ///have
        ///has
        ///had
        ///having
        ///do
        ///does
        ///did
        ///doing
        ///a
        ///an
        ///the
        ///and
        ///but
        ///if
        ///or
        ///because
        ///as
        ///until
        ///while
        ///of
        ///at
        ///by
        ///for
        ///with
        ///about
        ///against
        ///between
        ///into
        ///through
        ///during
        ///before
        ///after
        ///above
        ///below
        ///to
        ///from
        ///up
        ///down
        ///in
        ///out
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChineseJieba {
            get {
                return ResourceManager.GetString("ChineseJieba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnes
        ///cz
        ///timto
        ///budes
        ///budem
        ///byli
        ///jses
        ///muj
        ///svym
        ///ta
        ///tomto
        ///tohle
        ///tuto
        ///tyto
        ///jej
        ///zda
        ///proc
        ///mate
        ///tato
        ///kam
        ///tohoto
        ///kdo
        ///kteri
        ///mi
        ///nam
        ///tom
        ///tomuto
        ///mit
        ///nic
        ///proto
        ///kterou
        ///byla
        ///toho
        ///protoze
        ///asi
        ///ho
        ///nasi
        ///napiste
        ///re
        ///coz
        ///tim
        ///takze
        ///svych
        ///jeji
        ///svymi
        ///jste
        ///aj
        ///tu
        ///tedy
        ///teto
        ///bylo
        ///kde
        ///ke
        ///prave
        ///ji
        ///nad
        ///nejsou
        ///ci
        ///pod
        ///tema
        ///mezi
        ///pres
        ///ty
        ///pak
        ///vam
        ///ani
        ///kdyz
        ///vsak
        ///ne
        ///jsem
        ///tento
        ///clanku
        ///clanky
        ///aby
        ///jsme
        ///pred
        ///pta
        ///jejich
        ///byl
        ///jeste
        ///az
        ///bez
        ///take
        ///pouze
        ///prvni
        ///vase
        ///ktera
        ///na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string czechstoplist {
            get {
                return ResourceManager.GetString("czechstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///à
        ///â
        ///abord
        ///afin
        ///ah
        ///ai
        ///aie
        ///ainsi
        ///allaient
        ///allo
        ///allô
        ///allons
        ///après
        ///assez
        ///attendu
        ///au
        ///aucun
        ///aucune
        ///aujourd
        ///aujourd&apos;hui
        ///auquel
        ///aura
        ///auront
        ///aussi
        ///autre
        ///autres
        ///aux
        ///auxquelles
        ///auxquels
        ///avaient
        ///avais
        ///avait
        ///avant
        ///avec
        ///avoir
        ///ayant
        ///b
        ///bah
        ///beaucoup
        ///bien
        ///bigre
        ///boum
        ///bravo
        ///brrr
        ///c
        ///ça
        ///car
        ///ce
        ///ceci
        ///cela
        ///celle
        ///celle-ci
        ///celle-là
        ///celles
        ///celles-ci
        ///celles-là
        ///celui
        ///celui-ci
        ///celui-là
        ///cent
        ///cependant
        ///certain
        ///certaine
        ///certaines
        ///certains
        ///certes
        ///ces
        ///cet
        ///cette
        ///ceux
        ///ceux- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frenchstoplist {
            get {
                return ResourceManager.GetString("frenchstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///ab
        ///aber
        ///aber
        ///ach
        ///acht
        ///achte
        ///achten
        ///achter
        ///achtes
        ///ag
        ///alle
        ///allein
        ///allem
        ///allen
        ///aller
        ///allerdings
        ///alles
        ///allgemeinen
        ///als
        ///als
        ///also
        ///am
        ///an
        ///andere
        ///anderen
        ///andern
        ///anders
        ///au
        ///auch
        ///auch
        ///auf
        ///aus
        ///ausser
        ///außer
        ///ausserdem
        ///außerdem
        ///b
        ///bald
        ///bei
        ///beide
        ///beiden
        ///beim
        ///beispiel
        ///bekannt
        ///bereits
        ///besonders
        ///besser
        ///besten
        ///bin
        ///bis
        ///bisher
        ///bist
        ///c
        ///d
        ///da
        ///dabei
        ///dadurch
        ///dafür
        ///dagegen
        ///daher
        ///dahin
        ///dahinter
        ///damals
        ///damit
        ///danach
        ///daneben
        ///dank
        ///dann
        ///daran
        ///darauf
        ///daraus
        ///darf
        ///darfst
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string germanstoplist {
            get {
                return ResourceManager.GetString("germanstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///abba
        ///abban
        ///abból
        ///addig
        ///ahhoz
        ///ahol
        ///akár
        ///aki
        ///akik
        ///akkor
        ///alá
        ///alád
        ///alájuk
        ///alám
        ///alánk
        ///alapján
        ///alátok
        ///alatt
        ///alatta
        ///alattad
        ///alattam
        ///alattatok
        ///alattuk
        ///alattunk
        ///alól
        ///alóla
        ///alólad
        ///alólam
        ///alólatok
        ///alóluk
        ///alólunk
        ///által
        ///általában
        ///ám
        ///amely
        ///amelybol
        ///amelyek
        ///amelyekben
        ///amelyeket
        ///amelyet
        ///amelyik
        ///amelynek
        ///ami
        ///amíg
        ///amikor
        ///amit
        ///amott
        ///annak
        ///annál
        ///arra
        ///arról
        ///át
        ///attól
        ///az
        ///azért
        ///aznap
        ///azok
        ///azokat
        ///azokba
        ///azokban
        ///azokból
        ///azokért
        ///azokhoz
        ///azokig
        ///azokká
        ///azokkal
        ///azoknak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hungarianST {
            get {
                return ResourceManager.GetString("hungarianST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///abbastanza
        ///accidenti
        ///ad
        ///adesso
        ///affinche
        ///agli
        ///ahime
        ///ahimè
        ///ai
        ///al
        ///alcuna
        ///alcuni
        ///alcuno
        ///all
        ///alla
        ///alle
        ///allo
        ///altri
        ///altrimenti
        ///altro
        ///altrui
        ///anche
        ///ancora
        ///anni
        ///anno
        ///ansa
        ///assai
        ///attesa
        ///avanti
        ///avendo
        ///avente
        ///aver
        ///avere
        ///avete
        ///aveva
        ///avuta
        ///avute
        ///avuti
        ///avuto
        ///basta
        ///bene
        ///benissimo
        ///berlusconi
        ///brava
        ///bravo
        ///c
        ///casa
        ///caso
        ///cento
        ///certa
        ///certe
        ///certi
        ///certo
        ///che
        ///chi
        ///chicchessia
        ///chiunque
        ///ci
        ///ciascuna
        ///ciascuno
        ///cima
        ///cio
        ///ciò
        ///cioe
        ///cioè
        ///circa
        ///citta
        ///città
        ///codesta
        ///codesti
        ///code [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string italianstoplist {
            get {
                return ResourceManager.GetString("italianstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و
        ///در
        ///به
        ///از
        ///كه
        ///مي
        ///اين
        ///است
        ///را
        ///با
        ///هاي
        ///براي
        ///آن
        ///يك
        ///شود
        ///شده
        ///خود
        ///ها
        ///كرد
        ///شد
        ///اي
        ///تا
        ///كند
        ///بر
        ///بود
        ///گفت
        ///نيز
        ///وي
        ///هم
        ///كنند
        ///دارد
        ///ما
        ///كرده
        ///يا
        ///اما
        ///بايد
        ///دو
        ///اند
        ///هر
        ///خواهد
        ///او
        ///مورد
        ///آنها
        ///باشد
        ///ديگر
        ///مردم
        ///نمي
        ///بين
        ///پيش
        ///پس
        ///اگر
        ///همه
        ///صورت
        ///يكي
        ///هستند
        ///بي
        ///من
        ///دهد
        ///هزار
        ///نيست
        ///استفاده
        ///داد
        ///داشته
        ///راه
        ///داشت
        ///چه
        ///همچنين
        ///كردند
        ///داده
        ///بوده
        ///دارند
        ///همين
        ///ميليون
        ///سوي
        ///شوند
        ///بيشتر
        ///بسيار
        ///روي
        ///گرفته
        ///هايي
        ///تواند
        ///اول
        ///نام
        ///هيچ
        ///چند
        ///جديد
        ///بيش
        ///شدن
        ///كردن
        ///كنيم
        ///نشان
        ///حتي
        ///اينكه
        ///ولی
        ///توسط
        ///چنين
        ///برخي [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string persianST {
            get {
                return ResourceManager.GetString("persianST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ach
        ///aj
        ///albo
        ///bardzo
        ///bez
        ///bo
        ///być
        ///ci
        ///cię
        ///ciebie
        ///co
        ///czy
        ///daleko
        ///dla
        ///dlaczego
        ///dlatego
        ///do
        ///dobrze
        ///dokąd
        ///dość
        ///dużo
        ///dwa
        ///dwaj
        ///dwie
        ///dwoje
        ///dziś
        ///dzisiaj
        ///gdyby
        ///gdzie
        ///go
        ///ich
        ///ile
        ///im
        ///inny
        ///ja
        ///ją
        ///jak
        ///jakby
        ///jaki
        ///je
        ///jeden
        ///jedna
        ///jedno
        ///jego
        ///jej
        ///jemu
        ///jeśli
        ///jest
        ///jestem
        ///jeżeli
        ///już
        ///każdy
        ///kiedy
        ///kierunku
        ///kto
        ///ku
        ///lub
        ///ma
        ///mają
        ///mam
        ///mi
        ///mną
        ///mnie
        ///moi
        ///mój
        ///moja
        ///moje
        ///może
        ///mu
        ///my
        ///na
        ///nam
        ///nami
        ///nas
        ///nasi
        ///nasz
        ///nasza
        ///nasze
        ///natychmiast
        ///nią
        ///nic
        ///nich
        ///nie
        ///niego
        ///niej
        ///niemu
        ///nig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string polishST {
            get {
                return ResourceManager.GetString("polishST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to а
        ///е
        ///и
        ///ж
        ///м
        ///о
        ///на
        ///не
        ///ни
        ///об
        ///но
        ///он
        ///мне
        ///мои
        ///мож
        ///она
        ///они
        ///оно
        ///мной
        ///много
        ///многочисленное
        ///многочисленная
        ///многочисленные
        ///многочисленный
        ///мною
        ///мой
        ///мог
        ///могут
        ///можно
        ///может
        ///можхо
        ///мор
        ///моя
        ///моё
        ///мочь
        ///над
        ///нее
        ///оба
        ///нам
        ///нем
        ///нами
        ///ними
        ///мимо
        ///немного
        ///одной
        ///одного
        ///менее
        ///однажды
        ///однако
        ///меня
        ///нему
        ///меньше
        ///ней
        ///наверху
        ///него
        ///ниже
        ///мало
        ///надо
        ///один
        ///одиннадцать
        ///одиннадцатый
        ///назад
        ///наиболее
        ///недавно
        ///миллионов
        ///недалеко
        ///между
        ///низко
        ///меля
        ///нельзя
        ///нибудь
        ///непрерывно
        ///наконец
        ///никогда
        ///ник [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string russianstoplist {
            get {
                return ResourceManager.GetString("russianstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///acá
        ///acaba
        ///acabar
        ///acabo
        ///acerca
        ///acuerdo
        ///actualmente
        ///adelante
        ///además
        ///ademas
        ///agradecería
        ///ahí
        ///ahí
        ///ahora
        ///ahorita
        ///al
        ///ala
        ///algo
        ///alguien
        ///algun
        ///algún
        ///alguna
        ///alguna
        ///algunas
        ///algunas
        ///alguno
        ///alguno
        ///algunos
        ///algunos
        ///allá
        ///allí
        ///alrededor
        ///ambos
        ///ampliamos
        ///angie
        ///ante
        ///antes
        ///aparte
        ///apenas
        ///aquel
        ///aquellas
        ///aquellos
        ///aquí
        ///arriba
        ///así
        ///asi
        ///asunto
        ///atrás
        ///aun
        ///aún
        ///aunque
        ///aveces
        ///b
        ///baja
        ///bajo
        ///bastante
        ///bien
        ///buen
        ///buscar
        ///busco
        ///c
        ///cabe
        ///cada
        ///cada
        ///caer
        ///capaz
        ///capacidad
        ///casi
        ///caso
        ///cau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spanishstoplist {
            get {
                return ResourceManager.GetString("spanishstoplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///À
        ///AAH
        ///ABLE
        ///ABOUT
        ///ABOVE
        ///ABST
        ///ACCORDANCE
        ///ACCORDING
        ///ACCORDINGLY
        ///ACROSS
        ///ACT
        ///ACTUAL
        ///ACTUALLY
        ///ADDED
        ///ADIEU
        ///ADIOS
        ///ADJ
        ///AFTER
        ///AFTERWARDS
        ///AGAIN
        ///AGAINST
        ///AGO
        ///AH
        ///do+not
        ///be+not
        ///AHA
        ///AHEAD
        ///AHEM
        ///AHOY
        ///AIN&apos;T
        ///ALACK
        ///ALAS
        ///ALBEIT
        ///ALL
        ///ALLELUIA
        ///ALMOST
        ///ALOFT
        ///ALONG
        ///ALONGSIDE
        ///alot
        ///ALREADY
        ///ALSO
        ///ALTHO
        ///ALTHOUGH
        ///ALWAYS
        ///AM
        ///AMEN
        ///AMID
        ///AMIDST
        ///AMONG
        ///AMONGST
        ///AN
        ///AND
        ///ANOTHER
        ///ANTI
        ///ANY
        ///ANYBODY
        ///ANYHOW
        ///ANYMORE
        ///ANYONE
        ///ANYPLACE
        ///ANYTHING
        ///ANYTIME
        ///ANYWAY
        ///ANYWAYS
        ///ANYWHERE
        ///ANYWISE
        ///APART
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stoplist_english {
            get {
                return ResourceManager.GetString("stoplist_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///able
        ///about
        ///above
        ///according
        ///accordingly
        ///across
        ///actually
        ///after
        ///afterwards
        ///again
        ///against
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///always
        ///am
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///around
        ///as
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///b
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///beforehand
        ///behind
        ///being
        ///believe
        ///below
        ///besid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stoplist_mallet_en {
            get {
                return ResourceManager.GetString("stoplist_mallet_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `
        ///~
        ///!
        ///@
        ///#
        ///$
        ///%
        ///^
        ///&amp;
        ///*
        ///(
        ///)
        ///_
        ///+
        ///-
        ///–
        ///=
        ///[
        ///]
        ///\
        ///;
        ///&apos;
        ///,
        ///.
        ////
        ///{
        ///}
        ///|
        ///:
        ///&quot;
        ///&lt;
        ///&gt;
        ///?
        ///..
        ///...
        ///«
        ///««
        ///»»
        ///“
        ///”
        ///‘
        ///‘‘
        ///’
        ///’’
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///0
        ///10
        ///11
        ///12
        ///13
        ///14
        ///15
        ///16
        ///17
        ///18
        ///19
        ///20
        ///25
        ///30
        ///33
        ///40
        ///50
        ///60
        ///66
        ///70
        ///75
        ///80
        ///90
        ///99
        ///100
        ///123
        ///1000
        ///10000
        ///12345
        ///100000
        ///1000000.
        /// </summary>
        internal static string StopListCharacters {
            get {
                return ResourceManager.GetString("StopListCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///abir
        ///acaba
        ///alt
        ///altı
        ///altmış
        ///ama
        ///amp
        ///ancak
        ///arada
        ///aslında
        ///aynı
        ///ayrıca
        ///az
        ///b
        ///b
        ///bakan
        ///bana
        ///başka
        ///bazı
        ///bazı
        ///belki
        ///ben
        ///benden
        ///beni
        ///benim
        ///beri
        ///beş
        ///bile
        ///bin
        ///bir
        ///biraz
        ///birçok
        ///biri
        ///birkaç
        ///birkez
        ///birşey
        ///birşeyi
        ///biz
        ///bizden
        ///bize
        ///bizi
        ///bizim
        ///böyle
        ///böyle 
        ///böylece
        ///boyunca
        ///bu
        ///buna
        ///bunda
        ///bundan
        ///bunlar
        ///bunları
        ///bunların
        ///bunu
        ///bunun
        ///burada
        ///büyük
        ///c
        ///c
        ///Co
        ///co
        ///çoğu
        ///cok
        ///çok
        ///coskununyeri
        ///çünkü
        ///d
        ///da
        ///daha
        ///dahi
        ///de
        ///defa
        ///değil
        ///değil
        ///diğer
        ///diğer
        ///diye
        ///doksan
        ///dokuz
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string turkishstoplist {
            get {
                return ResourceManager.GetString("turkishstoplist", resourceCulture);
            }
        }
    }
}
